### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by myelin0** [myelin0/Recipe-app#12]
https://github.com/myelin0/Recipe-app/projects/1
There are 2 people on our team.
Team #1 myelin0
Team #2 Graycemuthui

**Comment by BenMukebo** [comment]
### Hi @myelin0, @Graycemuthui,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Link to your GitHub project. is present ✔️  
- The information about the number of people in your group is present ✔️ 
- Each requiremnts have at least one corresponding card in the Kanban board. ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Great job so far 👏🏻 However, all cards must be assigned to team members. there are tasks that have not yet been assigned to any team member, please add this ✍🏻 We should see a circle with the user's avatar on each card. See example below:

![image](https://user-images.githubusercontent.com/79058364/194841084-777c1dcf-a921-461c-a5e8-dc258691e9ac.png)

- Yours:

![Screenshot from 2022-10-10 11-48-08](https://user-images.githubusercontent.com/79058364/194840100-a90983b9-0f43-4616-893b-6eaa97cb18dd.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by myelin0** [comment]
@BenMukebo Thank you very much for your review. I fixed it.

**Comment by BenMukebo** [comment]
### Hi @myelin0, @Graycemuthui 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- All cards are assigned to team members. ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
